### PR TITLE
Updated the zip path

### PR DESCRIPTION
**Pull request by sagun98**
Hi @ljmciver, 

Seems like the additional check for the "decompressed files" was causing the issue. 

Additionally, checking Line 458 - output_prefix variable, it looks like __kneaddata is attached to it for all cases, therefore split('_') is not causing the issue.  

However, checking with Melanie's test files, it is weird that trimmomatic is just giving 1 output files as the other 3 expected output files sizes are 0.

### CODE REVIEW

**Comment by ljmciver** [comment]
HI @sagun98 , Thanks for the quick turn around on the pull request! I think there are a couple things that we need to change so that we cover all of the different use cases including Melanie's test files (which I also see producing a subset of fastqc files).

1. Update the code to allow for only the html file generated by fastqc. In this case there is no zip file so there are no adapters / over-represented sequences found. The code can just throw an informative message to the log to say something to this affect (ie  "no over-prepresented sequences found, bypassing filtering for these sequences"). This should cover the error in Melanie's small test files and also any user that runs with any small test files (or any other files that fastqc does not find adapters). 
2. Refactor the lines 453 - 548 in knead_data.py . 
  A. We want the code to be generic so it does not expect a "_" in the output_prefix. An example of this would be if a user ran a set of samples with names without underscores through the biobakery workflows (files with names like `ABCD123.fastq.gz, ABCD123.fastq.gz, etc`). The workflows set the output_prefix option and so the output prefix would not have any underscores so the fastqc output file name would not match that generated by fastqc (it would be something like `_fastqc.zip`). 
 B. It looks like in Melanie's case with her "real" input files (not the small set she sent us) fastqc does generate the html and the zip files but the file names look like they don't match up with what is expected in the code (I will copy them below for reference). I think it might be the extra underscore in the names that might not sync up.
  * I think for 2A and 2B if we refactor lines 453 - 548 to be more generic we can make them more flexible (I will copy them below for reference). Also I think we can change the input files to fastqc to just us the original user input files which will make guessing the fastqc output file name easier. I tested and checked their documents and they support sam, bam, and compressed fastq files (ie gzip, bunzip2). You can just save the paths to the original input files from the user before the array changes the file names and use these as the input to the `run.fastqc` function. Then you should have an easy time figuring out the fastqc output file names because they will just be the input file name minus the extension plus `_fastqc.[html|zip]`. I think this should be very extensible and generic and it should solve the couple of cases above. Also since the workflow writes all of the kneaddata output files to one folder this naming convention should work well and not cause any race conditions with file name conflicts which is great!

Please let me know if you have any questions for me about the next steps and I will also follow up with you on slack too.

Thanks,
Lauren

```
# Melanie's fastqc output file names
reformatted_identifiersds1vrshy_decompressed_9gwmbje__test_1_fastqc.html  reformatted_identifierskiz40vs9_decompressed_rdzvvkgk_test_2_fastqc.html
reformatted_identifiersds1vrshy_decompressed_9gwmbje__test_1_fastqc.zip   reformatted_identifierskiz40vs9_decompressed_rdzvvkgk_test_2_fastqc.zip
```

```
# lines to refactor (knead_data.py lines 453 - 548)
        #Setting fastqc output zip and txt file path
        if (args.input[0].count("reformatted_identifier"))>0 or (args.input[0].count("decompressed"))>0:
            zip_path =  args.output_dir+"/fastqc/"+'/'.join(args.input[0].split('/')[-1:])
            if (args.input[0].count("decompressed"))>0:
                zip_path= '.'.join(zip_path.split('.')[:-1])
        else: 
            zip_path =  args.output_dir+"/fastqc/"+'_'.join(args.output_prefix.split('_')[:-1])
        output_zip = zip_path+"_fastqc.zip"
        output_txt = zip_path+"_fastqc/fastqc_data.txt"
```

**Comment by sagun98** [comment]
Hi @ljmciver , 

Thanks for your detailed code review. Below are the changes: 
1. FASTQC is now extracting the zip file for us. Additionally, added the log message to yield if "no overrepresented sequences are found. " 

2.  The lines 453 - 548 in knead_data.py has been refactored. As you mentioned, I am now using the original output files and splitting with  "." to get the input file names. 

Note: After making these changes, I tested Melanie's test files, and trimmomatic was yielding empty files. The reason was, Trimmomatic was taking all the FASTQC overrepresented sequences (which in all the reads in this case) as adapters and was being removed, therefore yielding empty files. 
```
>>Overrepresented sequences in test_1/fastqc_data.txt
#Sequence       Count   Percentage      Possible Source
CGATACGAGCAATGCCACCGCTGAAGCGAGCAGCATGATCAGATACGGCC      1       2.0     No Hit
GATTGGTGTATTCCAGGAGGTCATGTTGATCCAGGGGAAACTTTCTTGCA      1       2.0     No Hit
GATCACGCACAAGACCTTGTCGGTTTCGGTATCGAACATCATATTGTTGA      1       2.0     No Hit
GGGTCAGGTTTTAACCTTCTCAACTACAAGGTAGTCCCCCTGCTTGAATA      1       2.0     No Hit
AGCGCGATACCATGAGCGACTGTTTGTTTTGTAAAATCGCCGGGGGAGAA      1       2.0     No Hit
CTGTGCTGATGGCTTTTGCCAGACCGATGCCAATAAATATAAAGTAAGCA      1       2.0     No Hit
...
...
``` 

I have set a new argument `--threshold-trim-repetitive` using which users will be able to set the threshold of the trimming of overrepresented sequences. By default, I have set the threshold to 5 because removing the low occurring overrepresented sequences below ~5% causes this issue. As mentioned in the call, it is basically trade-off between reading count and quality. 

Additionally, I have updated the README with some detailed descriptions and examples. Please let me know what you think about the above changes whenever you get a chance. 

Thanks,
Sagun

**Comment by ljmciver** [comment]
Hi @sagun98 , Thanks for the updates! I think the current changes look good. I am just confused about the new option.

Is the new option `--threshold-trim-repetitive <5>` a setting that has been through an eval and gotten the all clear? If not, should we add this as another pull in a dev branch? Also I see the code now reviews both fastqc output files if paired. I think that makes sense if there is possibly differences in each. Did you want to now have both read through instead of one?

Small nice to have changes (these should be quick easy and would be great to change if ok with you!):
1. The fastqc section currently does not allow for periods in the file names (a possible case but not one that we see all the time, so possibly okay to keep as is):
current line: `temp_file=input_file_name.split('.')[0]`
If you change this to remove: ".gz, .bzip2, .sam, .bam` and then remove `.fastq, or .fq` that should work.
2. We should add a catch in the code if the files you need from fastqc are not present (to print a message to the log and continue). I checked the test example from Melanie and it looks like it runs okay and does generate the data file you now use but it would just be good to include this catch just in case.
3. Since you have info printed to the log you can totally take out the print statements in the extract_fastqc_output function. This will make status a bit easier to track on stdout.

Please let me know if you have any questions. I will also follow up with you on slack.

Thanks!
Lauren

**Comment by sagun98** [comment]
Hi @ljmciver ,

I have removed the new option "--threshold-trim-repetitive <5>". Additionally, I have made the other minor changes that you mentioned as well.  

For Melanie's test files, using `--bypass-trim-repetitive` will skip the removal of FASTQC generated overrepresented sequence, and generate non-empty output files from trimmomatic.

**Comment by ljmciver** [comment]
Hi @sagun98 , Thanks for the changes! The new code to figure out the fastqc output file name looks great! I tested it with a couple different input file extensions plus periods in the file name and all worked well. I see the new catch in the read for the fastqc output file. Thanks for taking out the new dev feature for this current pull. 

Thank you!
Lauren

**Pull request merged**
