### PR TITLE
Defaults changed

### PR DESCRIPTION
**Pull request by sagun98**
Changes for this pull request: 

- Make TRF on by default and before bowtie2 step.
- Change name from --cut-adapters to --trim-repetitive.
- Make --trim-repetitive on by default and before trimmomatic step.

### CODE REVIEW

**Comment by ljmciver** [comment]
Hi @sagun98 , Thanks for the pull request and testing! It looks good! Just two sections that I think we need to change.

1. run.py line 534: We need to change this section a bit because it looks like it will drop one of the orphaned output files as is. If dropped this file will not be included in downstream processing.
2. knead_data.py line 544: I think this should stay the same as it is. I think with the change with some use cases it will print a line for each character in an output file. If the file list at this point is different then currently expected we should change it upstream because it would likely affect other sections of the code.

I will follow up with you on slack. Please let me know if you have any questions for me.

Thank you!
Lauren

**Comment by sagun98** [comment]
Hi @ljmciver, 

Thanks for the review. Below are the changes: 
1. run.py line 534: Agreed. Changed the code to not ignore "unmatched files". 
2. knead_data.py line 544: Agreed. Used the resolve_sublists to get the final output files. 

Please review the changes whenever you get the chance.

**Comment by ljmciver** [comment]
Hi @sagun98 , Thanks for the changes! I checked them all out in detail. I think the code in the run.py at line 534 (copied below for your reference) still needs to change a bit. The way that it is any orphan files will be dropped from the final set of output files (so will not pass to the decontamination steps). Since we are moving the trf function up in the workflow, before the bowtie2 step, the format of the output files list should be the same as expected prior. It should either be a list of two pairs or a list of a single file or a list of lists if there are orphans from prior steps in the workflow like trimmomatic. Check out the trimmomatic function to see what format the output_files list should be from the trf function now that we are moving it. I will follow up with you on slack. Please let me know if you have any questions for me.

```
    temp=[]
    if len(output_fastq_files)>1:
        for file in output_fastq_files:
            temp.append(file)
        output_files.append(temp)
```

**Comment by sagun98** [comment]
Hi @ljmciver , 

Many thanks for the review and the detailed comments. I have updated the code to match the trimmomatic output after the TRF step as well. I am keeping the pre-alignment steps after trimmomatic as it is in case if the user needs to bypass the TRF step and directly perform to decontamination. 

Please let me know if anything needs to be changed.

**Comment by ljmciver** [comment]
Hi @sagun98 , Thanks for iterating! Sorry this part is a bit complex but if we don't keep the pairs and orphans in place the downstream processing will be a bit quirky! I think the list that is returned from the trf step can't use the same code as the list that is returned from the trimmomatic step. I think what you could do which should keep everything in sync is to keep the same list structure that is input to trf as the output. For example if trf is provided with a list of pairs and orphans which would look like `[[pair1, pair2], [orphan1], [orphan2]]` then return this same list structure from the trf function. This should work with everything downstream. I don't think you would need to worry about the case of empty output files from trf like might happen with trimmomatic so it makes this function a bit simpler. Please let me know if you have any questions for me.  I will also ping you on slack to follow up!

Thanks!
Lauren

**Comment by ljmciver** [comment]
Hi @sagun98 , Thanks for the latest changes. Looks good!

Thank you!
Lauren

**Pull request merged**
