### PR TITLE
Feature/cut adapters

### PR DESCRIPTION
**Pull request by sagun98**
Cut adapter integration pull request.

### CODE REVIEW

**Comment by ljmciver** [comment]
Hi @sagun98 , Thanks for the pull request! Here are a few questions and suggestions.

1. For the adapter reading function, I think you want to capture the max seq length, right? Currently you would just capture the length of the last sequence in the list for the variable `overreq_seq_length` that is then returned and used for the trimming length. Also do you want to always remove the first and last sequences in the list that is created with `seq_list= overreq_seq_list[1:-1]` ? I am not sure exactly the output of fastqc with adapters so just wanted to double check with you on this one!
2. Change the location for the custom adapter file to a non-install folder (consider the output folder provided by the user). Where you currently have it we can never run two kneaddata tasks at the same time on the same machine if we run with this new option. Also if kneaddata was installed as root the user would need root permissions to write to the adapter file. If you change the file location to the output folder provided by the user then you should be set! I would say consider a more descriptive name for the file so the user knows what is included in it (maybe "adapters.fna").
3. The trimmomatic parameter modifications section only holds true for the case that the ILLUMINACLIP options are provided as the first item in the space delimited list (like is currently in the defaults). If you change this section of code to look for the ILLUMINACLIP section (if provided) and modify from there it will be more flexible and allow users to also provide custom trimmomatic options and use the adapter feature too.
4. Remove the extra files (.gitignore, and all the *.pyc files). We don't want to track and build with these files.
5. Reformat the following code `(int) (overreq_seq_length*0.6)` to a more standard python format.
6. Add back in the tests merged file (unless it is a file we no longer need).

Please post here or follow up with me on slack if you have any questions! I will also ping you on slack too.

Thanks,
Lauren

**Comment by sagun98** [comment]
Hi @ljmciver , 

Many thanks for the review. I have made the following changes based on the review: 

1. I have usually seen the length of the overrepresented sequence to be the same generated by FASTQC. However, great suggestion as there might be the case for variable overrepresented sequence length. Now I am taking the max overrepresented sequence length. 
 
For `seq_list= overreq_seq_list[1:-1]`, since the first and last element of the list is descriptions(`>>Overrepresented sequences` and `>>End Module`), those are being ignored. 
Example of fastqc output txt file:
```
...
...
>>Overrepresented sequences
ATGCATGCATGCATGCATGC
ATGCATAATGTGCTGCATGC
>>End Module
...
...
```

2. 100% agreed. Changed the adapters file output location to the kneaddata output directory + renamed the file to `adapters.fa`

3. 100% agreed. The function is now searching for "ILLUMINACLIP" instead of taking the 1st index of the list. 

4. Extra files (.gitignore, and all the *.pyc files, .github ) removed.

5. Reformatting the following code `(int) (overreq_seq_length*0.6)` to a more standard python format:  I was a bit confused about this one. I changed the code to `str(int(overreq_seq_length*0.6))` but not sure if it is more standard. Do you want me to put "0.6" in the config file or do float to integer to string conversion in a different way? Please advise.  

6. Added back in the tests merged file (Accidentally removed this earlier while testing).

**Comment by ljmciver** [comment]
Hi @sagun98 , Thank you! Looks great! The only tiny change I would make would be to return the path to the adapter file back from the function `extract_fastqc_output` so you can use it later in the code. This way you do not have to hard code it twice and if it changes in one location you don't need to worry about changing it in the second location. Great changes!

Thanks!
Lauren

**Comment by sagun98** [comment]
Hi @ljmciver,

I have added the extension of the adapter file in the  `extract_fastqc_output ` as well. 

Additionally, I forgot to account for the reformatted files earlier so added that as well.   
Please let me know if anything needs to be changed. 

Thanks,
Sagun

**Comment by ljmciver** [comment]
Thank you @sagun98 !

**Pull request merged**
